services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Application\Command\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }
        App\Application\Query\QueryHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

    App\:
        resource: '%kernel.project_dir%/src/'
        exclude:
            - '%kernel.project_dir%/src/Domain/'
            - '%kernel.project_dir%/src/Infrastructure/DependencyInjection/'
            - '%kernel.project_dir%/src/Infrastructure/Entity/'
            - '%kernel.project_dir%/src/Infrastructure/Kernel.php'
            - '%kernel.project_dir%/src/Infrastructure/Tests/'

    App\Infrastructure\Controller\:
        resource: '%kernel.project_dir%/src/Infrastructure/Controller/'
        tags: ['controller.service_arguments']

when@test_fake:
    services:
        _defaults:
            autowire: true
            autoconfigure: true

        App\Tests\Behat\:
            resource: '%kernel.project_dir%/tests/Behat/*'

when@test_real:
    services:
        _defaults:
            autowire: true
            autoconfigure: true

        App\Tests\Behat\:
            resource: '%kernel.project_dir%/tests/Behat/*'
